spring:
  application:
    name: hie-gateway
logging:
  pattern:
    console: "[%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n]"
  level:
    root: error
---
spring:
  config:
    activate:
      on-profile: dev
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - PATCH
            allowedHeaders: "*"
      routes:
        - id: auth
          uri: http://localhost:8089
          predicates:
            - Path=/api/v1/auth/**,
        - id: reports
          uri: http://localhost:9000
          predicates:
            - Path=/api/v1/reports/**
        - id: graphql-reports
          uri: http://localhost:9000
          predicates:
            - Path=/graphql/**
        - id: client
          uri: http://localhost:9002
          predicates:
            - Path=/api/v1/clients/**
        - id: referral
          uri: http://localhost:9003
          predicates:
            - Path=/api/v1/referral/**
        - id: lis
          uri: http://localhost:9010
          predicates:
            - Path=/api/v1/lis-service/**
        - id: pharmacy
          uri: http://localhost:9011
          predicates:
            - Path=/api/v1/pharmacy/**

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    urls:
      - name: auth
        url: http://localhost:8089/v3/api-docs
      - name: reports
        url: http://localhost:9000/v3/api-docs
      - name: client
        url: http://localhost:9002/v3/api-docs
      - name: referral
        url: http://localhost:9003/v3/api-docs
      - name: lis
        url: http://localhost:9010/v3/api-docs
      - name: pharmacy
        url: http://localhost:9011/v3/api-docs
    path: /swagger-ui.html

server:
  port: 7080
---
spring:
  config:
    activate:
      on-profile: prod
  cloud:
    gateway:
      default-filters:
        - name: AddResponseHeader
          args:
            name: "Referrer-Policy"
            value: "no-referrer-when-downgrade"
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowed-origin-patterns:
              - ${ALLOWED_ORIGINS}
            allowed-methods:
              - "*"
            allowedHeaders: "*"
            allowCredentials: true
            max-age: 3600
      x-forwarded:
        enabled: true
        for-enabled: true
        proto-enabled: true
        host-enabled: true
      routes:
        - id: auth
          uri: ${AUTH_URI}
          predicates:
            - Path=/api/v1/auth/**,
        - id: reports
          uri: ${REPORTS_URI}
          predicates:
            - Path=/api/v1/reports/**, /graphql/**
        - id: client
          uri: ${CLIENT_URI}
          predicates:
            - Path=/api/v1/clients/**
        - id: referral
          uri: ${REFERRAL_URI}
          predicates:
            - Path=/api/v1/referral/**
        - id: lis
          uri: ${LIS_URI}
          predicates:
            - Path=/api/v1/lis-service/**
        - id: pharmacy
          uri: ${PHARMACY_URI}
          predicates:
            - Path=/api/v1/pharmacy/**

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    urls:
      - name: auth
        url: ${AUTH_DOCS_URL}/v3/api-docs
      - name: reports
        url: ${REPORTS_DOCS_URL}/v3/api-docs
      - name: client
        url: ${CLIENT_DOCS_URL}/v3/api-docs
      - name: referral
        url: ${REFERRAL_DOCS_URL}/v3/api-docs
      - name: lis
        url: ${LIS_DOCS_URL}/v3/api-docs
      - name: pharmacy
        url: ${PHARMACY_URL}/v3/api-docs
    path: /swagger-ui.html

server:
  port: ${SERVER_PORT}
  forward-headers-strategy: framework